FROM golang:1.20

# Set the working directory inside the container
WORKDIR /app

# Copy the Go application source code into the container
COPY . .

# Build the Go application
RUN go build -o myapp

# Expose the port that the application will listen on
EXPOSE 8080

# Run the Go application when the container starts
# CMD ["./myapp", "worker"]
CMD "bash"
