// https://www.youtube.com/watch?v=jnnIgvV0_yA&list=PLCKpcjBB_VlBsxJ9IseNxFllf-UFEXOdg&index=114&ab_channel=AprendaGo
// the package is called encoding/json
// https://www.youtube.com/watch?v=-tU2PSY8F5w&list=PLCKpcjBB_VlBsxJ9IseNxFllf-UFEXOdg&index=114&ab_channel=AprendaGo

// json to go
// https://mholt.github.io/json-to-go/

package main

import (
	"encoding/json"
	"fmt"
)

type Person struct {
	Name        string
	Lastname    string
	Age         int
	Profession  string
	BankAccount float64
	// In Java and C, the type comes first
	// In Java, String is a class and not a primitive data type
	// that is why String is written with a capital S

	// In Java, we have the access modifier: public and private
	// to let the program know which ones are accessible from the outside
	// this is related to encapsulation and limiting what the program can do
	// in Go we use upper and lower letters to use access modifiers
	// If a variable, function or type is capitalized then it is public
}

func main() {
	Aragorn := Person{
		Name:        "Aragorn",
		Lastname:    "son of Arathorn",
		Age:         40,
		Profession:  "Strider",
		BankAccount: 9.0,
	}

	Obiwan := Person{
		Name:        "Obi-Wan",
		Lastname:    "Kenobi",
		Age:         65,
		Profession:  "Jedi",
		BankAccount: 1000000.0,
	}

	j, err := json.Marshal(Aragorn)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(j) // this will return a slice of bytes
	// but we want string
	fmt.Println(string(j))

	j, err = json.Marshal(Obiwan)

	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(string(j))

	// [123 34 78 97 109 101 34 58 34 65 114 97 103 111 114 110 34 44 34 76 97 115 116 110 97 109 101 34 58 34 115 111 110 32 111 102 32 65 114 97 116 104 111 114 110 34 44 34 65 103 101 34 58 52 48 44 34 80 114 111 102 101 115 115 105 111 110 34 58 34 83 116 114 105 100 101 114 34 44 34 66 97 110 107 65 99 99 111 117 110 116 34 58 57 125]
	// {"Name":"Aragorn","Lastname":"son of Arathorn","Age":40,"Profession":"Strider","BankAccount":9}
	// {"Name":"Obi-Wan","Lastname":"Kenobi","Age":65,"Profession":"Jedi","BankAccount":1000000}

	// pass this into json to go
	//
	// type AutoGenerated struct {
	// 	Name        string `json:"Name"`
	// 	Lastname    string `json:"Lastname"`
	// 	Age         int    `json:"Age"`
	// 	Profession  string `json:"Profession"`
	// 	BankAccount int    `json:"BankAccount"`
	// }

}

// next:
// https://www.youtube.com/watch?v=mcbj-wy8Ro8&list=PLCKpcjBB_VlBsxJ9IseNxFllf-UFEXOdg&index=115&ab_channel=AprendaGo
