
build:
	go build -o primary cmd/primary/main.go 
	go build -o secondary cmd/secondary/main.go 
	go build -o server cmd/server/main.go 
	go build -o test01 cmd/test01/main.go 


run:
	go build -o server cmd/server/main.go 
	./server
